### ISSUE TITLE
コンソールエラー Warning: findDOMNode is deprecated in StrictMode.

### ISSUE THREAD

**Issue by Helestia** [Helestia/moecost#3]
開発モードのコンソール上でのみ表示されるエラー
![image](https://user-images.githubusercontent.com/68133854/108820707-ee4bfe00-75ff-11eb-8db8-0445860ce98a.png)

### 問題の再現

開発モードで当プロジェクトを起動
正常完了後、下記動作のいずれかで該当エラー表示

1. 左上のメニューボタンを押してドローメニューを表示
2. レシピ表示後、概要テーブルの作成個数列をマウスオーバーして背景色を変更

おそらくその他の何らかの方法でも同様の警告が表示される。

### 対応について

当プロジェクトで使用しているUIライブラリであるmaterial-UIのリリース版の既知の問題。(該当Issue:https://github.com/mui-org/material-ui/issues/13394)
現在開発中のv.5代では問題は解消されているとのことだが、まだalpha版なので当プロジェクトでは現状非採用。このエラーを許容する方針でいる。
material-ui v5が正式リリースされた際に乗り換えるかどうか検討して対応する。

**Comment by partoneplay** [comment]
参考 [#13394](https://github.com/mui-org/material-ui/issues/13394)
彼らは日本語を知らない
英語を使ってください

**Comment by Helestia** [comment]
ご忠告ありがとうございます。該当Issueの状況を確認することを理由にリンクを張ったのですが、該当Issue側にも通知されることを認識しておりませんでした。

もしご迷惑をおかけしてしまったのでしたら謝罪いたします。

あくまでこの問題はこのプロジェクト上での問題であり、また開発時のみに発生する問題であるため、解決を急いでいるわけではありません。
v5の正式リリースを楽しみにしております。

---
Thank you for your advice. I made a link to check the status of the relevant issue, but I was not aware that the relevant issue would also be notified.

We apologize for any inconvenience caused.

This problem is a problem on this project, and it occurs only during development, so we are not in a hurry to solve it.
We are looking forward to the official release of v5.

**Comment by Helestia** [comment]
`MUI`は昨年11月あたりよりversion 5が正式リリースされてる。
大規模な修正が必要だが、やっぱり新UIは適用すべきだと考えている。

パフォーマンスの改善はもとより、当アプリで使用している`autoComplete`や`alert`がlabからcoreに移行したことも含めて、対応すべき案件だと思っています。

このIssueで該当作業を実施するよりは、別の「MUI V5適用作業」みたいなIssueを作成して、そちらで作業したほうがよさそうですので、そのようなIssueを建てる準備ができ次第このIssueはクローズします。

**Comment by Helestia** [comment]
サービス終了予定日が決まりましたため、このIssueはいったん凍結します。
